services:
  api:
    image: voasd00/noteus-api:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env.config
      - .env.secret


  db:
    image: voasd00/noteus-database:latest
    platform: linux/amd64
    ports:
      - "5000:5000"
    env_file:
      - .env.config
      - .env.secret
    depends_on:
      - api

  frontend:
    image: voasd00/noteus-frontend:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - .env.config
      - .env.secret
    depends_on:
      - api
      - db