  # Two services  
  services:
    # First Service
    redis:
      image: redis/redis-stack-server:latest
      container_name: redis
      restart: always
      
      # redis volumne data is mounted to persist data between container restarts 
      # Map the /data directory inside the container to the local redis_volume_data directory
      volumes:
        - redis_volume_data:/data
      ports:
        - 6379:6379
    
    # Second service - GRAPHICAL Interface for Managing Redis Database
    redis_insight:
      image: redislabs/redisinsight:1.14.0
      container_name: redis_insight
      restart: always
      ports:
        - 8001:8001
      volumes:
        - redis_insight_volume_data:/db

  volumes:
    redis_volume_data:
    redis_insight_volume_data: