version: '3.8'

services:
  api:
    image: voasd00/noteus-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: voasd00/noteus-database:latest
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    image: voasd00/noters-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
      - db