apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-frontend
  template:
    metadata:
      labels:
        app: noteus-frontend
    spec:
      containers:
        - name: noteus-frontend
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-frontend:latest
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-database
  template:
    metadata:
      labels:
        app: noteus-database
    spec:
      containers:
        - name: noteus-database
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-database:latest
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-api
  template:
    metadata:
      labels:
        app: noteus-api
    spec:
      containers:
        - name: noteus-api
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-api:latest
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config