apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-frontend
  template:
    metadata:
      labels:
        app: noteus-frontend
    spec:
      containers:
        - name: noteus-frontend
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-frontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXT_PUBLIC_APP_URL
            - name: NEXT_PUBLIC_BACKEND_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXT_PUBLIC_BACKEND_DB_URL
            - name: NEXT_PUBLIC_BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXT_PUBLIC_BACKEND_API_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXTAUTH_URL
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: NEXTAUTH_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: STRIPE_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-database
  template:
    metadata:
      labels:
        app: noteus-database
    spec:
      containers:
        - name: noteus-database
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-database:v1
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLOUDINARY_API_SECRET
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GOOGLE_API_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_URI
            - name: PORT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PORT_BACKEND
            - name: FRONTEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: FRONTEND_API_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteus-api
  template:
    metadata:
      labels:
        app: noteus-api
    spec:
      containers:
        - name: noteus-api
          image: asia-southeast2-docker.pkg.dev/neat-striker-455607-i3/noteus-repo/noteus-api:v1
          ports:
            - containerPort: 8000
          env:
            - name: ZILLIZ_CLOUD_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ZILLIZ_CLOUD_URI
            - name: ZILLIZ_CLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ZILLIZ_CLOUD_TOKEN
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LANGCHAIN_API_KEY
            - name: LANGCHAIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LANGCHAIN_ENDPOINT
            - name: USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: USER_AGENT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_COLLECTION_NAME
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GOOGLE_API_KEY
          resources:
            requests:
              memory: "256Mi"      # Minimum memory requested
              cpu: "250m"          # Minimum CPU requested
            limits:
              memory: "512Mi"      # Maximum memory allowed
              cpu: "500m"          # Maximum CPU allowed