name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - 'front-end/**'
      - 'database/**'
      - '.github/workflows/docker-image.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api, front-end, database]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}@gmail.com
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/noteus-${{ matrix.service }}:latest
