name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'

jobs:
  setup-build-publish-deploy:
    env:
      PROJECT_ID: 'neat-striker-455607-i3'  # TODO: update to your Google Cloud project ID
      GAR_LOCATION: 'asia-southeast2'  # TODO: update to your region
      GKE_CLUSTER: 'noteus-cluster'  # TODO: update to your cluster name
      GKE_ZONE: 'asia-southeast1-a'  # TODO: update to your cluster zone
      DEPLOYMENT_NAME_1: 'noteus-api'  # TODO: update to your deployment name
      DEPLOYMENT_NAME_2: 'noteus-frontend'  # TODO: update to your deployment name
      DEPLOYMENT_NAME_3: 'noteus-database'  # TODO: update to your deployment name
      REPOSITORY: 'noteus-repo'  # TODO: update to your Artifact Registry docker repository name
      WORKLOAD_IDENTITY_PROVIDER: 'projects/669663908735/locations/global/workloadIdentityPools/github-action-pool/providers/github'  # TODO: update to your workload identity provider

    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout the code from GitHub
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Authenticate to Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-wif@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
      # Create env.yaml file for Cloud Run
      - name: 'Generate Cloud Run env.yaml'
        run: |
          echo "envs:" > env.yaml
          echo "  - name: GOOGLE_CLIENT_ID" >> env.yaml
          echo "    value: \"${{ secrets.GOOGLE_CLIENT_ID }}\"" >> env.yaml
          echo "  - name: GOOGLE_CLIENT_SECRET" >> env.yaml
          echo "    value: \"${{ secrets.GOOGLE_CLIENT_SECRET }}\"" >> env.yaml
          echo "  - name: NEXTAUTH_SECRET" >> env.yaml
          echo "    value: \"${{ secrets.NEXTAUTH_SECRET }}\"" >> env.yaml
          echo "  - name: STRIPE_SECRET_KEY" >> env.yaml
          echo "    value: \"${{ secrets.STRIPE_SECRET_KEY }}\"" >> env.yaml
          echo "  - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" >> env.yaml
          echo "    value: \"${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}\"" >> env.yaml
          echo "  - name: JWT_SECRET" >> env.yaml
          echo "    value: \"${{ secrets.JWT_SECRET }}\"" >> env.yaml
          echo "  - name: CLOUDINARY_CLOUD_NAME" >> env.yaml
          echo "    value: \"${{ secrets.CLOUDINARY_CLOUD_NAME }}\"" >> env.yaml
          echo "  - name: CLOUDINARY_API_KEY" >> env.yaml
          echo "    value: \"${{ secrets.CLOUDINARY_API_KEY }}\"" >> env.yaml
          echo "  - name: CLOUDINARY_API_SECRET" >> env.yaml
          echo "    value: \"${{ secrets.CLOUDINARY_API_SECRET }}\"" >> env.yaml
          echo "  - name: GOOGLE_API_KEY" >> env.yaml
          echo "    value: \"${{ secrets.GOOGLE_API_KEY }}\"" >> env.yaml
          echo "  - name: MONGO_URI" >> env.yaml
          echo "    value: \"${{ secrets.MONGO_URI }}\"" >> env.yaml
          echo "  - name: MONGO_DB_NAME" >> env.yaml
          echo "    value: \"${{ secrets.MONGO_DB_NAME }}\"" >> env.yaml
          echo "  - name: MONGO_COLLECTION_NAME" >> env.yaml
          echo "    value: \"${{ secrets.MONGO_COLLECTION_NAME }}\"" >> env.yaml
          echo "  - name: OPENAI_API_KEY" >> env.yaml
          echo "    value: \"${{ secrets.OPENAI_API_KEY }}\"" >> env.yaml
          echo "  - name: ZILLIZ_CLOUD_URI" >> env.yaml
          echo "    value: \"${{ secrets.ZILLIZ_CLOUD_URI }}\"" >> env.yaml
          echo "  - name: ZILLIZ_CLOUD_TOKEN" >> env.yaml
          echo "    value: \"${{ secrets.ZILLIZ_CLOUD_TOKEN }}\"" >> env.yaml
          echo "  - name: LANGCHAIN_API_KEY" >> env.yaml
          echo "    value: \"${{ secrets.LANGCHAIN_API_KEY }}\"" >> env.yaml
          echo "  - name: LANGCHAIN_ENDPOINT" >> env.yaml
          echo "    value: \"${{ secrets.LANGCHAIN_ENDPOINT }}\"" >> env.yaml
          echo "  - name: USER_AGENT" >> env.yaml
          echo "    value: \"${{ secrets.USER_AGENT }}\"" >> env.yaml
          echo "  - name: HUGGINGFACE_TOKEN" >> env.yaml
          echo "    value: \"${{ secrets.HUGGINGFACE_TOKEN }}\"" >> env.yaml
          echo "  - name: NEXT_PUBLIC_APP_URL" >> env.yaml
          echo "    value: \"${{ vars.NEXT_PUBLIC_APP_URL }}\"" >> env.yaml
          echo "  - name: NEXT_PUBLIC_BACKEND_API_URL" >> env.yaml
          echo "    value: \"${{ vars.NEXT_PUBLIC_BACKEND_API_URL }}\"" >> env.yaml
          echo "  - name: NEXTAUTH_URL" >> env.yaml
          echo "    value: \"${{ vars.NEXTAUTH_URL }}\"" >> env.yaml
          echo "  - name: NEXT_PUBLIC_BACKEND_DB_URL" >> env.yaml
          echo "    value: \"${{ vars.NEXT_PUBLIC_BACKEND_DB_URL }}\"" >> env.yaml
          echo "  - name: FRONTEND_API_URL" >> env.yaml
          echo "    value: \"${{ vars.FRONTEND_API_URL }}\"" >> env.yaml
          echo "  - name: PORT_BACKEND" >> env.yaml
          echo "    value: \"${{ vars.PORT_BACKEND }}\"" >> env.yaml
      # Authenticate Docker to Google Cloud Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'  # Ensure this outputs the correct token
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          
      # Build and push Docker containers for all three services
      - name: 'Build and push Docker containers'
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain
          FRONTEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-frontend:latest"
          DATABASE_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-database:latest"
          API_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-api:latest"
      
          # Set your build arguments
          echo "Building frontend container: $FRONTEND_TAG"
          docker build "${BUILD_ARGS[@]}" -f front-end/Dockerfile --tag "${FRONTEND_TAG}" front-end/
          docker push "${FRONTEND_TAG}"

          echo "Building database container: $DATABASE_TAG"
          docker build -f database/Dockerfile --tag "${DATABASE_TAG}" database/
          docker push "${DATABASE_TAG}"

          echo "Building API container: $API_TAG"
          docker build -f api/Dockerfile --tag "${API_TAG}" api/
          docker push "${API_TAG}"

      

      - name: 'Deploy Frontend to Cloud Run'
        run: |
          gcloud run deploy noteus-frontend \
            --image=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-frontend:latest \
            --region=${GAR_LOCATION} \
            --platform=managed \
            --allow-unauthenticated \
            --env-vars-file=env.yaml

      - name: 'Deploy API to Cloud Run'
        run: |
          gcloud run deploy noteus-api \
            --image=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-api:latest \
            --region=${GAR_LOCATION} \
            --platform=managed \
            --allow-unauthenticated \
            --env-vars-file=env.yaml

      - name: 'Deploy Database to Cloud Run'
        run: |
          gcloud run deploy noteus-database \
            --image=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/noteus-database:latest \
            --region=${GAR_LOCATION} \
            --platform=managed \
            --allow-unauthenticated